// app/layout.tsx
import type { Metadata } from 'next';
import './globals.css';
import { Urbanist } from 'next/font/google';

import { AuthProvider } from '@/context/AuthContext';
import { OnboardingProvider } from '@/context/OnboardingContext';
import { LoadingProvider } from '@/context/LoadingContext'; // Add this import

import Providers from './provider';

const urbanist = Urbanist({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
    apple: '/favicon.ico',
    shortcut: '/favicon.ico',
  },
  openGraph: {
    title: 'CT3 Exam System',
    description: 'Activity logging and exam generation dashboard',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${urbanist.className} antialiased`}>
        <AuthProvider>
          <OnboardingProvider>
            <LoadingProvider> {/* Add this provider */}
              {children}
            </LoadingProvider>
          </OnboardingProvider>
        </AuthProvider>
      </body>
    </html>
  );
}